import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ja' | 'ko' | 'zh' | 'es' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'hero.title': 'Your Magical Travel Companion',
    'hero.subtitle': 'AI-powered travel planning with seamless connectivity worldwide',
    'hero.cta': 'Start Planning',
    'features.ai': 'AI Planning',
    'features.esim': 'Global eSIM',
    'features.realtime': 'Real-time Updates',
    'nav.home': 'Home',
    'nav.plan': 'Plan Trip',
    'nav.dashboard': 'Dashboard',
    'planning.destination': 'Where would you like to go?',
    'planning.dates': 'When are you traveling?',
    'planning.budget': 'What\'s your budget?',
    'planning.style': 'Travel Style',
    'planning.companions': 'Who\'s joining you?',
    // PaymentScreen
    'paymentscreen.title': 'Payment',
    'paymentscreen.no_plan': 'No plan selected.',
    'paymentscreen.agree': 'I agree to the Terms of Service',
    'paymentscreen.pay': 'Pay with Stripe',
    'paymentscreen.note': 'You will be redirected to Stripe for secure payment.',
    'paymentscreen.secure': 'Your payment is protected by Stripe.',
    // QRCodeScreen
    'qrscreen.title': 'eSIM Activation',
    'qrscreen.no_plan': 'No plan selected.',
    'qrscreen.desc': 'Scan the QR code below to activate your eSIM.',
    'qrscreen.loading': 'Issuing your eSIM... Please wait.',
    'qrscreen.copy': 'Copy QR URL',
    'qrscreen.download': 'Download QR',
    'qrscreen.note': 'If you have trouble, contact support.',
    'qrscreen.copied': 'Copied!',
    'qrscreen.step1': 'Open your device settings and select "Add Mobile Plan".',
    'qrscreen.step2': 'Scan the QR code above with your device.',
    'qrscreen.step3': 'Follow the on-screen instructions to complete activation.',
    'qrscreen.goto_dashboard': 'Go to Dashboard',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading your plans...',
    'dashboard.no_plans': 'No travel plans found.',
    'dashboard.active': 'Active',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.completed': 'Completed',
    'dashboard.details': 'Details',
    'dashboard.show_qr': 'Show eSIM QR',
    'dashboard.esim_active': 'eSIM Active',
    'dashboard.esim_expired': 'eSIM Expired',
    'dashboard.esim_pending': 'eSIM Pending',
    // Review
    'review.title': 'User Reviews',
    'review.your_rating': 'Your Rating',
    'review.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.latest': 'Latest Reviews',
    'review.loading': 'Loading reviews...',
    'review.no_reviews': 'No reviews yet.',
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.search': 'Search FAQ...',
    'faq.all': 'All',
    'faq.loading': 'Loading FAQs...',
    'faq.no_results': 'No FAQs found.',
    // AdminDashboard
    'admin.title': 'Admin Dashboard',
    'admin.tab_users': 'Users',
    'admin.tab_plans': 'Plans',
    'admin.tab_faqs': 'FAQs',
    'admin.tab_reviews': 'Reviews',
    'admin.users': 'User Management',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.plans': 'Plan Management',
    'admin.price': 'Price',
    'admin.faqs': 'FAQ Management',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.category': 'Category',
    'admin.reviews': 'Review Management',
    'admin.user': 'User',
    'admin.comment': 'Comment',
    'admin.rating': 'Rating',
    'admin.date': 'Date',
    'admin.kpi_mau': 'Monthly Active Users',
    'admin.kpi_new_users': 'New Users',
    'admin.kpi_sales': 'Sales',
    'admin.kpi_esim': 'eSIM Issued',
    'admin.kpi_sales_trend': 'Sales Trend (¥)',
    'admin.kpi_esim_trend': 'eSIM Issued Trend',
    // AIChat
    'aichat.placeholder': 'Ask about your trip, edit your plan, or get local support…',
    'aichat.thinking': 'AI is thinking…',
    'aichat.default_reply': 'Thank you for your question. Here is a detailed answer.',
    'aichat.error': 'Failed to get AI response. Please try again.',
    'aichat.uploading': 'Uploading image and recognizing text…',
    'aichat.ocr_result': 'OCR result:',
    'aichat.translated': 'Translated:',
    'aichat.ocr_error': 'Failed to recognize or translate the image.',
    'nav.language': 'Language',
    'nav.plan_preview': 'Plan Preview',
    'nav.esim': 'eSIM Plans',
    'nav.payment': 'Payment',
    'nav.esim_qr': 'eSIM Activation',
    'nav.reviews': 'Reviews',
    'nav.devices': 'Devices',
    'nav.faq': 'FAQ/Support',
    'nav.admin': 'Admin',
  },
  ja: {
    'hero.title': 'あなたの魔法の旅の相棒',
    'hero.subtitle': 'AI搭載の旅行計画と世界中でのシームレスな接続',
    'hero.cta': '計画を始める',
    'features.ai': 'AI計画',
    'features.esim': 'グローバルeSIM',
    'features.realtime': 'リアルタイム更新',
    'nav.home': 'ホーム',
    'nav.plan': '旅行計画',
    'nav.dashboard': 'ダッシュボード',
    'planning.destination': 'どちらに行きたいですか？',
    'planning.dates': 'いつ旅行しますか？',
    'planning.budget': '予算はいくらですか？',
    'planning.style': '旅行スタイル',
    'planning.companions': '誰と一緒に行きますか？',
    // PaymentScreen
    'paymentscreen.title': 'お支払い',
    'paymentscreen.no_plan': 'プランが選択されていません。',
    'paymentscreen.agree': '利用規約に同意します',
    'paymentscreen.pay': 'Stripeで支払う',
    'paymentscreen.note': '安全な決済のためStripeにリダイレクトされます。',
    'paymentscreen.secure': 'お支払いはStripeで保護されています。',
    // QRCodeScreen
    'qrscreen.title': 'eSIMアクティベーション',
    'qrscreen.no_plan': 'プランが選択されていません。',
    'qrscreen.desc': '下記のQRコードをスキャンしてeSIMを有効化してください。',
    'qrscreen.loading': 'eSIMを発行中です...しばらくお待ちください。',
    'qrscreen.copy': 'QRのURLをコピー',
    'qrscreen.download': 'QRをダウンロード',
    'qrscreen.note': 'うまくいかない場合はサポートまでご連絡ください。',
    'qrscreen.copied': 'コピーしました！',
    'qrscreen.step1': '端末の設定から「モバイル通信プランを追加」を選択。',
    'qrscreen.step2': '上記QRコードを端末でスキャン。',
    'qrscreen.step3': '画面の案内に従いeSIMを有効化。',
    'qrscreen.goto_dashboard': 'ダッシュボードへ',
    // Dashboard
    'dashboard.title': 'ダッシュボード',
    'dashboard.loading': 'プラン情報を読み込み中...',
    'dashboard.no_plans': '旅行プランがありません。',
    'dashboard.active': '利用中',
    'dashboard.upcoming': '予約済み',
    'dashboard.completed': '完了',
    'dashboard.details': '詳細',
    'dashboard.show_qr': 'eSIM QR表示',
    'dashboard.esim_active': 'eSIM利用中',
    'dashboard.esim_expired': 'eSIM期限切れ',
    'dashboard.esim_pending': 'eSIM未発行',
    // Review
    'review.title': 'ユーザーレビュー',
    'review.your_rating': 'あなたの評価',
    'review.placeholder': '体験の感想をシェアしてください...',
    'review.submit': 'レビューを投稿',
    'review.latest': '最新のレビュー',
    'review.loading': 'レビューを読み込み中...',
    'review.no_reviews': 'まだレビューがありません。',
    // FAQ
    'faq.title': 'よくあるご質問',
    'faq.search': 'FAQを検索...',
    'faq.all': 'すべて',
    'faq.loading': 'FAQを読み込み中...',
    'faq.no_results': '該当するFAQがありません。',
    // AdminDashboard
    'admin.title': '管理者ダッシュボード',
    'admin.tab_users': 'ユーザー',
    'admin.tab_plans': 'プラン',
    'admin.tab_faqs': 'FAQ',
    'admin.tab_reviews': 'レビュー',
    'admin.users': 'ユーザー管理',
    'admin.name': '名前',
    'admin.email': 'メール',
    'admin.role': '権限',
    'admin.plans': 'プラン管理',
    'admin.price': '価格',
    'admin.faqs': 'FAQ管理',
    'admin.question': '質問',
    'admin.answer': '回答',
    'admin.category': 'カテゴリ',
    'admin.reviews': 'レビュー管理',
    'admin.user': 'ユーザー',
    'admin.comment': 'コメント',
    'admin.rating': '評価',
    'admin.date': '日付',
    'admin.kpi_mau': '月間アクティブユーザー',
    'admin.kpi_new_users': '新規登録',
    'admin.kpi_sales': '売上',
    'admin.kpi_esim': 'eSIM発行数',
    'admin.kpi_sales_trend': '売上推移（円）',
    'admin.kpi_esim_trend': 'eSIM発行数推移',
    // AIChat
    'aichat.placeholder': '旅の相談やプランの変更、現地サポートはこちら…',
    'aichat.thinking': 'AIが考え中…',
    'aichat.default_reply': 'ご質問ありがとうございます。詳しくお答えします。',
    'aichat.error': 'AI応答に失敗しました。もう一度お試しください。',
    'aichat.uploading': '画像をアップロードして文字認識中…',
    'aichat.ocr_result': 'OCR結果:',
    'aichat.translated': '翻訳結果:',
    'aichat.ocr_error': '画像の認識または翻訳に失敗しました。',
    'nav.language': '言語選択',
    'nav.plan_preview': 'プランプレビュー',
    'nav.esim': 'eSIMプラン',
    'nav.payment': 'お支払い',
    'nav.esim_qr': 'eSIMアクティベーション',
    'nav.reviews': '体験レビュー',
    'nav.devices': 'デバイス一覧',
    'nav.faq': 'FAQ/サポート',
    'nav.admin': '管理者',
  },
  ko: {
    'hero.title': '당신의 마법 같은 여행 동반자',
    'hero.subtitle': 'AI 기반 여행 계획과 전 세계 어디서나 원활한 연결',
    'hero.cta': '여행 계획 시작',
    'features.ai': 'AI 여행 계획',
    'features.esim': '글로벌 eSIM',
    'features.realtime': '실시간 업데이트',
    'nav.home': '홈',
    'nav.plan': '여행 계획',
    'nav.dashboard': '대시보드',
    'planning.destination': '어디로 가고 싶으신가요?',
    'planning.dates': '언제 여행하시나요?',
    'planning.budget': '예산은 얼마인가요?',
    'planning.style': '여행 스타일',
    'planning.companions': '누구와 함께 가시나요?',
    // PaymentScreen
    'paymentscreen.title': '결제',
    'paymentscreen.no_plan': '선택된 플랜이 없습니다.',
    'paymentscreen.agree': '이용약관에 동의합니다',
    'paymentscreen.pay': 'Stripe로 결제',
    'paymentscreen.note': '안전한 결제를 위해 Stripe로 이동합니다.',
    'paymentscreen.secure': '결제는 Stripe로 보호됩니다.',
    // QRCodeScreen
    'qrscreen.title': 'eSIM 활성화',
    'qrscreen.no_plan': '선택된 플랜이 없습니다.',
    'qrscreen.desc': '아래 QR 코드를 스캔하여 eSIM을 활성화하세요.',
    'qrscreen.loading': 'eSIM 발급 중... 잠시만 기다려주세요.',
    'qrscreen.copy': 'QR URL 복사',
    'qrscreen.download': 'QR 다운로드',
    'qrscreen.note': '문제가 있으면 지원팀에 문의하세요.',
    'qrscreen.copied': '복사됨!',
    'qrscreen.step1': '기기 설정에서 "모바일 요금제 추가"를 선택하세요.',
    'qrscreen.step2': '위의 QR 코드를 기기로 스캔하세요.',
    'qrscreen.step3': '화면 안내에 따라 활성화를 완료하세요.',
    'qrscreen.goto_dashboard': '대시보드로 이동',
    // Dashboard
    'dashboard.title': '대시보드',
    'dashboard.loading': '플랜을 불러오는 중...',
    'dashboard.no_plans': '여행 플랜이 없습니다.',
    'dashboard.active': '활성',
    'dashboard.upcoming': '예정',
    'dashboard.completed': '완료',
    'dashboard.details': '상세',
    'dashboard.show_qr': 'eSIM QR 보기',
    'dashboard.esim_active': 'eSIM 활성화됨',
    'dashboard.esim_expired': 'eSIM 만료됨',
    'dashboard.esim_pending': 'eSIM 대기 중',
    // Review
    'review.title': '사용자 리뷰',
    'review.your_rating': '내 평점',
    'review.placeholder': '경험을 공유해 주세요...',
    'review.submit': '리뷰 제출',
    'review.latest': '최신 리뷰',
    'review.loading': '리뷰 불러오는 중...',
    'review.no_reviews': '아직 리뷰가 없습니다.',
    // FAQ
    'faq.title': '자주 묻는 질문',
    'faq.search': 'FAQ 검색...',
    'faq.all': '전체',
    'faq.loading': 'FAQ 불러오는 중...',
    'faq.no_results': '해당 FAQ가 없습니다.',
    // AdminDashboard
    'admin.title': '관리자 대시보드',
    'admin.tab_users': '사용자',
    'admin.tab_plans': '플랜',
    'admin.tab_faqs': 'FAQ',
    'admin.tab_reviews': '리뷰',
    'admin.users': '사용자 관리',
    'admin.name': '이름',
    'admin.email': '이메일',
    'admin.role': '권한',
    'admin.plans': '플랜 관리',
    'admin.price': '가격',
    'admin.faqs': 'FAQ 관리',
    'admin.question': '질문',
    'admin.answer': '답변',
    'admin.category': '카테고리',
    'admin.reviews': '리뷰 관리',
    'admin.user': '사용자',
    'admin.comment': '코멘트',
    'admin.rating': '평점',
    'admin.date': '날짜',
    'admin.kpi_mau': '월간 활성 사용자',
    'admin.kpi_new_users': '신규 사용자',
    'admin.kpi_sales': '매출',
    'admin.kpi_esim': 'eSIM 발급',
    'admin.kpi_sales_trend': '매출 추이(¥)',
    'admin.kpi_esim_trend': 'eSIM 발급 추이',
    // AIChat
    'aichat.placeholder': '여행, 플랜 수정, 현지 지원에 대해 문의하세요…',
    'aichat.thinking': 'AI가 생각 중…',
    'aichat.default_reply': '질문해 주셔서 감사합니다. 자세히 답변드리겠습니다.',
    'aichat.error': 'AI 응답에 실패했습니다. 다시 시도해 주세요.',
    'aichat.uploading': '이미지 업로드 및 문자 인식 중…',
    'aichat.ocr_result': 'OCR 결과:',
    'aichat.translated': '번역:',
    'aichat.ocr_error': '이미지 인식 또는 번역에 실패했습니다.',
    'nav.language': '언어 선택',
    'nav.plan_preview': '플랜 미리보기',
    'nav.esim': 'eSIM 플랜',
    'nav.payment': '결제',
    'nav.esim_qr': 'eSIM 활성화',
    'nav.reviews': '리뷰',
    'nav.devices': '디바이스 목록',
    'nav.faq': 'FAQ/지원',
    'nav.admin': '관리자',
  },
  zh: {
    'hero.title': '您的魔法旅行伙伴',
    'hero.subtitle': 'AI驱动的旅行规划，全球无缝连接',
    'hero.cta': '开始规划',
    'features.ai': 'AI规划',
    'features.esim': '全球eSIM',
    'features.realtime': '实时更新',
    'nav.home': '首页',
    'nav.plan': '旅行规划',
    'nav.dashboard': '仪表盘',
    'planning.destination': '您想去哪里？',
    'planning.dates': '您什么时候出行？',
    'planning.budget': '您的预算是多少？',
    'planning.style': '旅行风格',
    'planning.companions': '谁会和您一起？',
    // PaymentScreen
    'paymentscreen.title': '支付',
    'paymentscreen.no_plan': '未选择方案。',
    'paymentscreen.agree': '同意服务条款',
    'paymentscreen.pay': '使用Stripe支付',
    'paymentscreen.note': '将跳转至Stripe进行安全支付。',
    'paymentscreen.secure': '您的支付由Stripe保护。',
    // QRCodeScreen
    'qrscreen.title': 'eSIM激活',
    'qrscreen.no_plan': '未选择方案。',
    'qrscreen.desc': '请扫描下方二维码激活eSIM。',
    'qrscreen.loading': 'eSIM发放中...请稍候。',
    'qrscreen.copy': '复制QR链接',
    'qrscreen.download': '下载QR',
    'qrscreen.note': '如有问题请联系客服。',
    'qrscreen.copied': '已复制！',
    'qrscreen.step1': '在设备设置中选择“添加移动套餐”。',
    'qrscreen.step2': '用设备扫描上方二维码。',
    'qrscreen.step3': '按照屏幕指示完成激活。',
    'qrscreen.goto_dashboard': '前往仪表盘',
    // Dashboard
    'dashboard.title': '仪表盘',
    'dashboard.loading': '正在加载您的方案...',
    'dashboard.no_plans': '未找到旅行方案。',
    'dashboard.active': '已激活',
    'dashboard.upcoming': '即将到来',
    'dashboard.completed': '已完成',
    'dashboard.details': '详情',
    'dashboard.show_qr': '显示eSIM QR',
    'dashboard.esim_active': 'eSIM已激活',
    'dashboard.esim_expired': 'eSIM已过期',
    'dashboard.esim_pending': 'eSIM待处理',
    // Review
    'review.title': '用户评价',
    'review.your_rating': '您的评分',
    'review.placeholder': '分享您的体验...',
    'review.submit': '提交评价',
    'review.latest': '最新评价',
    'review.loading': '正在加载评价...',
    'review.no_reviews': '暂无评价。',
    // FAQ
    'faq.title': '常见问题',
    'faq.search': '搜索FAQ...',
    'faq.all': '全部',
    'faq.loading': '正在加载FAQ...',
    'faq.no_results': '未找到相关FAQ。',
    // AdminDashboard
    'admin.title': '管理员仪表盘',
    'admin.tab_users': '用户',
    'admin.tab_plans': '方案',
    'admin.tab_faqs': 'FAQ',
    'admin.tab_reviews': '评价',
    'admin.users': '用户管理',
    'admin.name': '姓名',
    'admin.email': '邮箱',
    'admin.role': '权限',
    'admin.plans': '方案管理',
    'admin.price': '价格',
    'admin.faqs': 'FAQ管理',
    'admin.question': '问题',
    'admin.answer': '回答',
    'admin.category': '类别',
    'admin.reviews': '评价管理',
    'admin.user': '用户',
    'admin.comment': '评论',
    'admin.rating': '评分',
    'admin.date': '日期',
    'admin.kpi_mau': '月活跃用户',
    'admin.kpi_new_users': '新用户',
    'admin.kpi_sales': '销售额',
    'admin.kpi_esim': 'eSIM发放量',
    'admin.kpi_sales_trend': '销售趋势(¥)',
    'admin.kpi_esim_trend': 'eSIM发放趋势',
    // AIChat
    'aichat.placeholder': '咨询旅行、编辑方案或获取本地支持…',
    'aichat.thinking': 'AI思考中…',
    'aichat.default_reply': '感谢您的提问。以下是详细解答。',
    'aichat.error': '获取AI回复失败，请重试。',
    'aichat.uploading': '正在上传图片并识别文字…',
    'aichat.ocr_result': 'OCR结果:',
    'aichat.translated': '翻译：',
    'aichat.ocr_error': '图片识别或翻译失败。',
    'nav.language': '语言选择',
    'nav.plan_preview': '方案预览',
    'nav.esim': 'eSIM方案',
    'nav.payment': '支付',
    'nav.esim_qr': 'eSIM激活',
    'nav.reviews': '评价',
    'nav.devices': '设备列表',
    'nav.faq': 'FAQ/支持',
    'nav.admin': '管理员',
  },
  es: {
    'hero.title': 'Your Magical Travel Companion',
    'hero.subtitle': 'AI-powered travel planning with seamless connectivity worldwide',
    'hero.cta': 'Start Planning',
    'features.ai': 'AI Planning',
    'features.esim': 'Global eSIM',
    'features.realtime': 'Real-time Updates',
    'nav.home': 'Home',
    'nav.plan': 'Plan Trip',
    'nav.dashboard': 'Dashboard',
    'planning.destination': 'Where would you like to go?',
    'planning.dates': 'When are you traveling?',
    'planning.budget': 'What\'s your budget?',
    'planning.style': 'Travel Style',
    'planning.companions': 'Who\'s joining you?',
    // PaymentScreen (enコピー)
    'paymentscreen.title': 'Payment',
    'paymentscreen.no_plan': 'No plan selected.',
    'paymentscreen.agree': 'I agree to the Terms of Service',
    'paymentscreen.pay': 'Pay with Stripe',
    'paymentscreen.note': 'You will be redirected to Stripe for secure payment.',
    'paymentscreen.secure': 'Your payment is protected by Stripe.',
    // QRCodeScreen (enコピー)
    'qrscreen.title': 'eSIM Activation',
    'qrscreen.no_plan': 'No plan selected.',
    'qrscreen.desc': 'Scan the QR code below to activate your eSIM.',
    'qrscreen.loading': 'Issuing your eSIM... Please wait.',
    'qrscreen.copy': 'Copy QR URL',
    'qrscreen.download': 'Download QR',
    'qrscreen.note': 'If you have trouble, contact support.',
    'qrscreen.copied': 'Copied!',
    'qrscreen.step1': 'Open your device settings and select "Add Mobile Plan".',
    'qrscreen.step2': 'Scan the QR code above with your device.',
    'qrscreen.step3': 'Follow the on-screen instructions to complete activation.',
    'qrscreen.goto_dashboard': 'Go to Dashboard',
    // Dashboard (enコピー)
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading your plans...',
    'dashboard.no_plans': 'No travel plans found.',
    'dashboard.active': 'Active',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.completed': 'Completed',
    'dashboard.details': 'Details',
    'dashboard.show_qr': 'Show eSIM QR',
    'dashboard.esim_active': 'eSIM Active',
    'dashboard.esim_expired': 'eSIM Expired',
    'dashboard.esim_pending': 'eSIM Pending',
    // Review (enコピー)
    'review.title': 'User Reviews',
    'review.your_rating': 'Your Rating',
    'review.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.latest': 'Latest Reviews',
    'review.loading': 'Loading reviews...',
    'review.no_reviews': 'No reviews yet.',
    // FAQ (enコピー)
    'faq.title': 'Frequently Asked Questions',
    'faq.search': 'Search FAQ...',
    'faq.all': 'All',
    'faq.loading': 'Loading FAQs...',
    'faq.no_results': 'No FAQs found.',
    // AdminDashboard (enコピー)
    'admin.title': 'Admin Dashboard',
    'admin.tab_users': 'Users',
    'admin.tab_plans': 'Plans',
    'admin.tab_faqs': 'FAQs',
    'admin.tab_reviews': 'Reviews',
    'admin.users': 'User Management',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.plans': 'Plan Management',
    'admin.price': 'Price',
    'admin.faqs': 'FAQ Management',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.category': 'Category',
    'admin.reviews': 'Review Management',
    'admin.user': 'User',
    'admin.comment': 'Comment',
    'admin.rating': 'Rating',
    'admin.date': 'Date',
    'admin.kpi_mau': 'Monthly Active Users',
    'admin.kpi_new_users': 'New Users',
    'admin.kpi_sales': 'Sales',
    'admin.kpi_esim': 'eSIM Issued',
    'admin.kpi_sales_trend': 'Sales Trend (¥)',
    'admin.kpi_esim_trend': 'eSIM Issued Trend',
    // AIChat (enコピー)
    'aichat.placeholder': 'Ask about your trip, edit your plan, or get local support…',
    'aichat.thinking': 'AI is thinking…',
    'aichat.default_reply': 'Thank you for your question. Here is a detailed answer.',
    'aichat.error': 'Failed to get AI response. Please try again.',
    'aichat.uploading': 'Uploading image and recognizing text…',
    'aichat.ocr_result': 'OCR result:',
    'aichat.translated': 'Translated:',
    'aichat.ocr_error': 'Failed to recognize or translate the image.',
    'nav.language': 'Language',
    'nav.plan_preview': 'Plan Preview',
    'nav.esim': 'eSIM Plans',
    'nav.payment': 'Payment',
    'nav.esim_qr': 'eSIM Activation',
    'nav.reviews': 'Reviews',
    'nav.devices': 'Devices',
    'nav.faq': 'FAQ/Support',
    'nav.admin': 'Admin',
  },
  fr: {
    'hero.title': 'Your Magical Travel Companion',
    'hero.subtitle': 'AI-powered travel planning with seamless connectivity worldwide',
    'hero.cta': 'Start Planning',
    'features.ai': 'AI Planning',
    'features.esim': 'Global eSIM',
    'features.realtime': 'Real-time Updates',
    'nav.home': 'Home',
    'nav.plan': 'Plan Trip',
    'nav.dashboard': 'Dashboard',
    'planning.destination': 'Where would you like to go?',
    'planning.dates': 'When are you traveling?',
    'planning.budget': 'What\'s your budget?',
    'planning.style': 'Travel Style',
    'planning.companions': 'Who\'s joining you?',
    // PaymentScreen (enコピー)
    'paymentscreen.title': 'Payment',
    'paymentscreen.no_plan': 'No plan selected.',
    'paymentscreen.agree': 'I agree to the Terms of Service',
    'paymentscreen.pay': 'Pay with Stripe',
    'paymentscreen.note': 'You will be redirected to Stripe for secure payment.',
    'paymentscreen.secure': 'Your payment is protected by Stripe.',
    // QRCodeScreen (enコピー)
    'qrscreen.title': 'eSIM Activation',
    'qrscreen.no_plan': 'No plan selected.',
    'qrscreen.desc': 'Scan the QR code below to activate your eSIM.',
    'qrscreen.loading': 'Issuing your eSIM... Please wait.',
    'qrscreen.copy': 'Copy QR URL',
    'qrscreen.download': 'Download QR',
    'qrscreen.note': 'If you have trouble, contact support.',
    'qrscreen.copied': 'Copied!',
    'qrscreen.step1': 'Open your device settings and select "Add Mobile Plan".',
    'qrscreen.step2': 'Scan the QR code above with your device.',
    'qrscreen.step3': 'Follow the on-screen instructions to complete activation.',
    'qrscreen.goto_dashboard': 'Go to Dashboard',
    // Dashboard (enコピー)
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading your plans...',
    'dashboard.no_plans': 'No travel plans found.',
    'dashboard.active': 'Active',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.completed': 'Completed',
    'dashboard.details': 'Details',
    'dashboard.show_qr': 'Show eSIM QR',
    'dashboard.esim_active': 'eSIM Active',
    'dashboard.esim_expired': 'eSIM Expired',
    'dashboard.esim_pending': 'eSIM Pending',
    // Review (enコピー)
    'review.title': 'User Reviews',
    'review.your_rating': 'Your Rating',
    'review.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.latest': 'Latest Reviews',
    'review.loading': 'Loading reviews...',
    'review.no_reviews': 'No reviews yet.',
    // FAQ (enコピー)
    'faq.title': 'Frequently Asked Questions',
    'faq.search': 'Search FAQ...',
    'faq.all': 'All',
    'faq.loading': 'Loading FAQs...',
    'faq.no_results': 'No FAQs found.',
    // AdminDashboard (enコピー)
    'admin.title': 'Admin Dashboard',
    'admin.tab_users': 'Users',
    'admin.tab_plans': 'Plans',
    'admin.tab_faqs': 'FAQs',
    'admin.tab_reviews': 'Reviews',
    'admin.users': 'User Management',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.plans': 'Plan Management',
    'admin.price': 'Price',
    'admin.faqs': 'FAQ Management',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.category': 'Category',
    'admin.reviews': 'Review Management',
    'admin.user': 'User',
    'admin.comment': 'Comment',
    'admin.rating': 'Rating',
    'admin.date': 'Date',
    'admin.kpi_mau': 'Monthly Active Users',
    'admin.kpi_new_users': 'New Users',
    'admin.kpi_sales': 'Sales',
    'admin.kpi_esim': 'eSIM Issued',
    'admin.kpi_sales_trend': 'Sales Trend (¥)',
    'admin.kpi_esim_trend': 'eSIM Issued Trend',
    // AIChat (enコピー)
    'aichat.placeholder': 'Ask about your trip, edit your plan, or get local support…',
    'aichat.thinking': 'AI is thinking…',
    'aichat.default_reply': 'Thank you for your question. Here is a detailed answer.',
    'aichat.error': 'Failed to get AI response. Please try again.',
    'aichat.uploading': 'Uploading image and recognizing text…',
    'aichat.ocr_result': 'OCR result:',
    'aichat.translated': 'Translated:',
    'aichat.ocr_error': 'Failed to recognize or translate the image.',
    'nav.language': 'Language',
    'nav.plan_preview': 'Plan Preview',
    'nav.esim': 'eSIM Plans',
    'nav.payment': 'Payment',
    'nav.esim_qr': 'eSIM Activation',
    'nav.reviews': 'Reviews',
    'nav.devices': 'Devices',
    'nav.faq': 'FAQ/Support',
    'nav.admin': 'Admin',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};