import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ja' | 'ko' | 'zh' | 'es' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'hero.title': 'Your Magical Travel Companion',
    'hero.subtitle': 'AI-powered travel planning with seamless connectivity worldwide',
    'hero.cta': 'Start Planning',
    'features.ai': 'AI Planning',
    'features.esim': 'Global eSIM',
    'features.realtime': 'Real-time Updates',
    'nav.home': 'Home',
    'nav.plan': 'Plan Trip',
    'nav.dashboard': 'Dashboard',
    'planning.destination': 'Where would you like to go?',
    'planning.dates': 'When are you traveling?',
    'planning.budget': 'What\'s your budget?',
    'planning.style': 'Travel Style',
    'planning.companions': 'Who\'s joining you?',
    // PaymentScreen
    'paymentscreen.title': 'Payment',
    'paymentscreen.no_plan': 'No plan selected.',
    'paymentscreen.agree': 'I agree to the Terms of Service',
    'paymentscreen.pay': 'Pay with Stripe',
    'paymentscreen.note': 'You will be redirected to Stripe for secure payment.',
    'paymentscreen.secure': 'Your payment is protected by Stripe.',
    // QRCodeScreen
    'qrscreen.title': 'eSIM Activation',
    'qrscreen.no_plan': 'No plan selected.',
    'qrscreen.desc': 'Scan the QR code below to activate your eSIM.',
    'qrscreen.loading': 'Issuing your eSIM... Please wait.',
    'qrscreen.copy': 'Copy QR URL',
    'qrscreen.download': 'Download QR',
    'qrscreen.note': 'If you have trouble, contact support.',
    'qrscreen.copied': 'Copied!',
    'qrscreen.step1': 'Open your device settings and select "Add Mobile Plan".',
    'qrscreen.step2': 'Scan the QR code above with your device.',
    'qrscreen.step3': 'Follow the on-screen instructions to complete activation.',
    'qrscreen.goto_dashboard': 'Go to Dashboard',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading your plans...',
    'dashboard.no_plans': 'No travel plans found.',
    'dashboard.active': 'Active',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.completed': 'Completed',
    'dashboard.details': 'Details',
    'dashboard.show_qr': 'Show eSIM QR',
    'dashboard.esim_active': 'eSIM Active',
    'dashboard.esim_expired': 'eSIM Expired',
    'dashboard.esim_pending': 'eSIM Pending',
    // Review
    'review.title': 'User Reviews',
    'review.your_rating': 'Your Rating',
    'review.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.latest': 'Latest Reviews',
    'review.loading': 'Loading reviews...',
    'review.no_reviews': 'No reviews yet.',
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.search': 'Search FAQ...',
    'faq.all': 'All',
    'faq.loading': 'Loading FAQs...',
    'faq.no_results': 'No FAQs found.',
    // AdminDashboard
    'admin.title': 'Admin Dashboard',
    'admin.tab_users': 'Users',
    'admin.tab_plans': 'Plans',
    'admin.tab_faqs': 'FAQs',
    'admin.tab_reviews': 'Reviews',
    'admin.users': 'User Management',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.plans': 'Plan Management',
    'admin.price': 'Price',
    'admin.faqs': 'FAQ Management',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.category': 'Category',
    'admin.reviews': 'Review Management',
    'admin.user': 'User',
    'admin.comment': 'Comment',
    'admin.rating': 'Rating',
    'admin.date': 'Date',
    'admin.kpi_mau': 'Monthly Active Users',
    'admin.kpi_new_users': 'New Users',
    'admin.kpi_sales': 'Sales',
    'admin.kpi_esim': 'eSIM Issued',
    'admin.kpi_sales_trend': 'Sales Trend (¥)',
    'admin.kpi_esim_trend': 'eSIM Issued Trend',
    // AIChat
    'aichat.placeholder': 'Ask about your trip, edit your plan, or get local support…',
    'aichat.thinking': 'AI is thinking…',
    'aichat.default_reply': 'Thank you for your question. Here is a detailed answer.',
    'aichat.error': 'Failed to get AI response. Please try again.',
    'aichat.uploading': 'Uploading image and recognizing text…',
    'aichat.ocr_result': 'OCR result:',
    'aichat.translated': 'Translated:',
    'aichat.ocr_error': 'Failed to recognize or translate the image.',
  },
  ja: {
    'hero.title': 'あなたの魔法の旅の相棒',
    'hero.subtitle': 'AI搭載の旅行計画と世界中でのシームレスな接続',
    'hero.cta': '計画を始める',
    'features.ai': 'AI計画',
    'features.esim': 'グローバルeSIM',
    'features.realtime': 'リアルタイム更新',
    'nav.home': 'ホーム',
    'nav.plan': '旅行計画',
    'nav.dashboard': 'ダッシュボード',
    'planning.destination': 'どちらに行きたいですか？',
    'planning.dates': 'いつ旅行しますか？',
    'planning.budget': '予算はいくらですか？',
    'planning.style': '旅行スタイル',
    'planning.companions': '誰と一緒に行きますか？',
    // PaymentScreen
    'paymentscreen.title': 'お支払い',
    'paymentscreen.no_plan': 'プランが選択されていません。',
    'paymentscreen.agree': '利用規約に同意します',
    'paymentscreen.pay': 'Stripeで支払う',
    'paymentscreen.note': '安全な決済のためStripeにリダイレクトされます。',
    'paymentscreen.secure': 'お支払いはStripeで保護されています。',
    // QRCodeScreen
    'qrscreen.title': 'eSIMアクティベーション',
    'qrscreen.no_plan': 'プランが選択されていません。',
    'qrscreen.desc': '下記のQRコードをスキャンしてeSIMを有効化してください。',
    'qrscreen.loading': 'eSIMを発行中です...しばらくお待ちください。',
    'qrscreen.copy': 'QRのURLをコピー',
    'qrscreen.download': 'QRをダウンロード',
    'qrscreen.note': 'うまくいかない場合はサポートまでご連絡ください。',
    'qrscreen.copied': 'コピーしました！',
    'qrscreen.step1': '端末の設定から「モバイル通信プランを追加」を選択。',
    'qrscreen.step2': '上記QRコードを端末でスキャン。',
    'qrscreen.step3': '画面の案内に従いeSIMを有効化。',
    'qrscreen.goto_dashboard': 'ダッシュボードへ',
    // Dashboard
    'dashboard.title': 'ダッシュボード',
    'dashboard.loading': 'プラン情報を読み込み中...',
    'dashboard.no_plans': '旅行プランがありません。',
    'dashboard.active': '利用中',
    'dashboard.upcoming': '予約済み',
    'dashboard.completed': '完了',
    'dashboard.details': '詳細',
    'dashboard.show_qr': 'eSIM QR表示',
    'dashboard.esim_active': 'eSIM利用中',
    'dashboard.esim_expired': 'eSIM期限切れ',
    'dashboard.esim_pending': 'eSIM未発行',
    // Review
    'review.title': 'ユーザーレビュー',
    'review.your_rating': 'あなたの評価',
    'review.placeholder': '体験の感想をシェアしてください...',
    'review.submit': 'レビューを投稿',
    'review.latest': '最新のレビュー',
    'review.loading': 'レビューを読み込み中...',
    'review.no_reviews': 'まだレビューがありません。',
    // FAQ
    'faq.title': 'よくあるご質問',
    'faq.search': 'FAQを検索...',
    'faq.all': 'すべて',
    'faq.loading': 'FAQを読み込み中...',
    'faq.no_results': '該当するFAQがありません。',
    // AdminDashboard
    'admin.title': '管理者ダッシュボード',
    'admin.tab_users': 'ユーザー',
    'admin.tab_plans': 'プラン',
    'admin.tab_faqs': 'FAQ',
    'admin.tab_reviews': 'レビュー',
    'admin.users': 'ユーザー管理',
    'admin.name': '名前',
    'admin.email': 'メール',
    'admin.role': '権限',
    'admin.plans': 'プラン管理',
    'admin.price': '価格',
    'admin.faqs': 'FAQ管理',
    'admin.question': '質問',
    'admin.answer': '回答',
    'admin.category': 'カテゴリ',
    'admin.reviews': 'レビュー管理',
    'admin.user': 'ユーザー',
    'admin.comment': 'コメント',
    'admin.rating': '評価',
    'admin.date': '日付',
    'admin.kpi_mau': '月間アクティブユーザー',
    'admin.kpi_new_users': '新規登録',
    'admin.kpi_sales': '売上',
    'admin.kpi_esim': 'eSIM発行数',
    'admin.kpi_sales_trend': '売上推移（円）',
    'admin.kpi_esim_trend': 'eSIM発行数推移',
    // AIChat
    'aichat.placeholder': '旅の相談やプランの変更、現地サポートはこちら…',
    'aichat.thinking': 'AIが考え中…',
    'aichat.default_reply': 'ご質問ありがとうございます。詳しくお答えします。',
    'aichat.error': 'AI応答に失敗しました。もう一度お試しください。',
    'aichat.uploading': '画像をアップロードして文字認識中…',
    'aichat.ocr_result': 'OCR結果:',
    'aichat.translated': '翻訳結果:',
    'aichat.ocr_error': '画像の認識または翻訳に失敗しました。',
  },
  ko: {
    'hero.title': 'Your Magical Travel Companion',
    'hero.subtitle': 'AI-powered travel planning with seamless connectivity worldwide',
    'hero.cta': 'Start Planning',
    'features.ai': 'AI Planning',
    'features.esim': 'Global eSIM',
    'features.realtime': 'Real-time Updates',
    'nav.home': 'Home',
    'nav.plan': 'Plan Trip',
    'nav.dashboard': 'Dashboard',
    'planning.destination': 'Where would you like to go?',
    'planning.dates': 'When are you traveling?',
    'planning.budget': 'What\'s your budget?',
    'planning.style': 'Travel Style',
    'planning.companions': 'Who\'s joining you?',
    // PaymentScreen (enコピー)
    'paymentscreen.title': 'Payment',
    'paymentscreen.no_plan': 'No plan selected.',
    'paymentscreen.agree': 'I agree to the Terms of Service',
    'paymentscreen.pay': 'Pay with Stripe',
    'paymentscreen.note': 'You will be redirected to Stripe for secure payment.',
    'paymentscreen.secure': 'Your payment is protected by Stripe.',
    // QRCodeScreen (enコピー)
    'qrscreen.title': 'eSIM Activation',
    'qrscreen.no_plan': 'No plan selected.',
    'qrscreen.desc': 'Scan the QR code below to activate your eSIM.',
    'qrscreen.loading': 'Issuing your eSIM... Please wait.',
    'qrscreen.copy': 'Copy QR URL',
    'qrscreen.download': 'Download QR',
    'qrscreen.note': 'If you have trouble, contact support.',
    'qrscreen.copied': 'Copied!',
    'qrscreen.step1': 'Open your device settings and select "Add Mobile Plan".',
    'qrscreen.step2': 'Scan the QR code above with your device.',
    'qrscreen.step3': 'Follow the on-screen instructions to complete activation.',
    'qrscreen.goto_dashboard': 'Go to Dashboard',
    // Dashboard (enコピー)
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading your plans...',
    'dashboard.no_plans': 'No travel plans found.',
    'dashboard.active': 'Active',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.completed': 'Completed',
    'dashboard.details': 'Details',
    'dashboard.show_qr': 'Show eSIM QR',
    'dashboard.esim_active': 'eSIM Active',
    'dashboard.esim_expired': 'eSIM Expired',
    'dashboard.esim_pending': 'eSIM Pending',
    // Review (enコピー)
    'review.title': 'User Reviews',
    'review.your_rating': 'Your Rating',
    'review.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.latest': 'Latest Reviews',
    'review.loading': 'Loading reviews...',
    'review.no_reviews': 'No reviews yet.',
    // FAQ (enコピー)
    'faq.title': 'Frequently Asked Questions',
    'faq.search': 'Search FAQ...',
    'faq.all': 'All',
    'faq.loading': 'Loading FAQs...',
    'faq.no_results': 'No FAQs found.',
    // AdminDashboard (enコピー)
    'admin.title': 'Admin Dashboard',
    'admin.tab_users': 'Users',
    'admin.tab_plans': 'Plans',
    'admin.tab_faqs': 'FAQs',
    'admin.tab_reviews': 'Reviews',
    'admin.users': 'User Management',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.plans': 'Plan Management',
    'admin.price': 'Price',
    'admin.faqs': 'FAQ Management',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.category': 'Category',
    'admin.reviews': 'Review Management',
    'admin.user': 'User',
    'admin.comment': 'Comment',
    'admin.rating': 'Rating',
    'admin.date': 'Date',
    'admin.kpi_mau': 'Monthly Active Users',
    'admin.kpi_new_users': 'New Users',
    'admin.kpi_sales': 'Sales',
    'admin.kpi_esim': 'eSIM Issued',
    'admin.kpi_sales_trend': 'Sales Trend (¥)',
    'admin.kpi_esim_trend': 'eSIM Issued Trend',
    // AIChat (enコピー)
    'aichat.placeholder': 'Ask about your trip, edit your plan, or get local support…',
    'aichat.thinking': 'AI is thinking…',
    'aichat.default_reply': 'Thank you for your question. Here is a detailed answer.',
    'aichat.error': 'Failed to get AI response. Please try again.',
    'aichat.uploading': 'Uploading image and recognizing text…',
    'aichat.ocr_result': 'OCR result:',
    'aichat.translated': 'Translated:',
    'aichat.ocr_error': 'Failed to recognize or translate the image.',
  },
  zh: {
    'hero.title': 'Your Magical Travel Companion',
    'hero.subtitle': 'AI-powered travel planning with seamless connectivity worldwide',
    'hero.cta': 'Start Planning',
    'features.ai': 'AI Planning',
    'features.esim': 'Global eSIM',
    'features.realtime': 'Real-time Updates',
    'nav.home': 'Home',
    'nav.plan': 'Plan Trip',
    'nav.dashboard': 'Dashboard',
    'planning.destination': 'Where would you like to go?',
    'planning.dates': 'When are you traveling?',
    'planning.budget': 'What\'s your budget?',
    'planning.style': 'Travel Style',
    'planning.companions': 'Who\'s joining you?',
    // PaymentScreen (enコピー)
    'paymentscreen.title': 'Payment',
    'paymentscreen.no_plan': 'No plan selected.',
    'paymentscreen.agree': 'I agree to the Terms of Service',
    'paymentscreen.pay': 'Pay with Stripe',
    'paymentscreen.note': 'You will be redirected to Stripe for secure payment.',
    'paymentscreen.secure': 'Your payment is protected by Stripe.',
    // QRCodeScreen (enコピー)
    'qrscreen.title': 'eSIM Activation',
    'qrscreen.no_plan': 'No plan selected.',
    'qrscreen.desc': 'Scan the QR code below to activate your eSIM.',
    'qrscreen.loading': 'Issuing your eSIM... Please wait.',
    'qrscreen.copy': 'Copy QR URL',
    'qrscreen.download': 'Download QR',
    'qrscreen.note': 'If you have trouble, contact support.',
    'qrscreen.copied': 'Copied!',
    'qrscreen.step1': 'Open your device settings and select "Add Mobile Plan".',
    'qrscreen.step2': 'Scan the QR code above with your device.',
    'qrscreen.step3': 'Follow the on-screen instructions to complete activation.',
    'qrscreen.goto_dashboard': 'Go to Dashboard',
    // Dashboard (enコピー)
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading your plans...',
    'dashboard.no_plans': 'No travel plans found.',
    'dashboard.active': 'Active',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.completed': 'Completed',
    'dashboard.details': 'Details',
    'dashboard.show_qr': 'Show eSIM QR',
    'dashboard.esim_active': 'eSIM Active',
    'dashboard.esim_expired': 'eSIM Expired',
    'dashboard.esim_pending': 'eSIM Pending',
    // Review (enコピー)
    'review.title': 'User Reviews',
    'review.your_rating': 'Your Rating',
    'review.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.latest': 'Latest Reviews',
    'review.loading': 'Loading reviews...',
    'review.no_reviews': 'No reviews yet.',
    // FAQ (enコピー)
    'faq.title': 'Frequently Asked Questions',
    'faq.search': 'Search FAQ...',
    'faq.all': 'All',
    'faq.loading': 'Loading FAQs...',
    'faq.no_results': 'No FAQs found.',
    // AdminDashboard (enコピー)
    'admin.title': 'Admin Dashboard',
    'admin.tab_users': 'Users',
    'admin.tab_plans': 'Plans',
    'admin.tab_faqs': 'FAQs',
    'admin.tab_reviews': 'Reviews',
    'admin.users': 'User Management',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.plans': 'Plan Management',
    'admin.price': 'Price',
    'admin.faqs': 'FAQ Management',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.category': 'Category',
    'admin.reviews': 'Review Management',
    'admin.user': 'User',
    'admin.comment': 'Comment',
    'admin.rating': 'Rating',
    'admin.date': 'Date',
    'admin.kpi_mau': 'Monthly Active Users',
    'admin.kpi_new_users': 'New Users',
    'admin.kpi_sales': 'Sales',
    'admin.kpi_esim': 'eSIM Issued',
    'admin.kpi_sales_trend': 'Sales Trend (¥)',
    'admin.kpi_esim_trend': 'eSIM Issued Trend',
    // AIChat (enコピー)
    'aichat.placeholder': 'Ask about your trip, edit your plan, or get local support…',
    'aichat.thinking': 'AI is thinking…',
    'aichat.default_reply': 'Thank you for your question. Here is a detailed answer.',
    'aichat.error': 'Failed to get AI response. Please try again.',
    'aichat.uploading': 'Uploading image and recognizing text…',
    'aichat.ocr_result': 'OCR result:',
    'aichat.translated': 'Translated:',
    'aichat.ocr_error': 'Failed to recognize or translate the image.',
  },
  es: {
    'hero.title': 'Your Magical Travel Companion',
    'hero.subtitle': 'AI-powered travel planning with seamless connectivity worldwide',
    'hero.cta': 'Start Planning',
    'features.ai': 'AI Planning',
    'features.esim': 'Global eSIM',
    'features.realtime': 'Real-time Updates',
    'nav.home': 'Home',
    'nav.plan': 'Plan Trip',
    'nav.dashboard': 'Dashboard',
    'planning.destination': 'Where would you like to go?',
    'planning.dates': 'When are you traveling?',
    'planning.budget': 'What\'s your budget?',
    'planning.style': 'Travel Style',
    'planning.companions': 'Who\'s joining you?',
    // PaymentScreen (enコピー)
    'paymentscreen.title': 'Payment',
    'paymentscreen.no_plan': 'No plan selected.',
    'paymentscreen.agree': 'I agree to the Terms of Service',
    'paymentscreen.pay': 'Pay with Stripe',
    'paymentscreen.note': 'You will be redirected to Stripe for secure payment.',
    'paymentscreen.secure': 'Your payment is protected by Stripe.',
    // QRCodeScreen (enコピー)
    'qrscreen.title': 'eSIM Activation',
    'qrscreen.no_plan': 'No plan selected.',
    'qrscreen.desc': 'Scan the QR code below to activate your eSIM.',
    'qrscreen.loading': 'Issuing your eSIM... Please wait.',
    'qrscreen.copy': 'Copy QR URL',
    'qrscreen.download': 'Download QR',
    'qrscreen.note': 'If you have trouble, contact support.',
    'qrscreen.copied': 'Copied!',
    'qrscreen.step1': 'Open your device settings and select "Add Mobile Plan".',
    'qrscreen.step2': 'Scan the QR code above with your device.',
    'qrscreen.step3': 'Follow the on-screen instructions to complete activation.',
    'qrscreen.goto_dashboard': 'Go to Dashboard',
    // Dashboard (enコピー)
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading your plans...',
    'dashboard.no_plans': 'No travel plans found.',
    'dashboard.active': 'Active',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.completed': 'Completed',
    'dashboard.details': 'Details',
    'dashboard.show_qr': 'Show eSIM QR',
    'dashboard.esim_active': 'eSIM Active',
    'dashboard.esim_expired': 'eSIM Expired',
    'dashboard.esim_pending': 'eSIM Pending',
    // Review (enコピー)
    'review.title': 'User Reviews',
    'review.your_rating': 'Your Rating',
    'review.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.latest': 'Latest Reviews',
    'review.loading': 'Loading reviews...',
    'review.no_reviews': 'No reviews yet.',
    // FAQ (enコピー)
    'faq.title': 'Frequently Asked Questions',
    'faq.search': 'Search FAQ...',
    'faq.all': 'All',
    'faq.loading': 'Loading FAQs...',
    'faq.no_results': 'No FAQs found.',
    // AdminDashboard (enコピー)
    'admin.title': 'Admin Dashboard',
    'admin.tab_users': 'Users',
    'admin.tab_plans': 'Plans',
    'admin.tab_faqs': 'FAQs',
    'admin.tab_reviews': 'Reviews',
    'admin.users': 'User Management',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.plans': 'Plan Management',
    'admin.price': 'Price',
    'admin.faqs': 'FAQ Management',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.category': 'Category',
    'admin.reviews': 'Review Management',
    'admin.user': 'User',
    'admin.comment': 'Comment',
    'admin.rating': 'Rating',
    'admin.date': 'Date',
    'admin.kpi_mau': 'Monthly Active Users',
    'admin.kpi_new_users': 'New Users',
    'admin.kpi_sales': 'Sales',
    'admin.kpi_esim': 'eSIM Issued',
    'admin.kpi_sales_trend': 'Sales Trend (¥)',
    'admin.kpi_esim_trend': 'eSIM Issued Trend',
    // AIChat (enコピー)
    'aichat.placeholder': 'Ask about your trip, edit your plan, or get local support…',
    'aichat.thinking': 'AI is thinking…',
    'aichat.default_reply': 'Thank you for your question. Here is a detailed answer.',
    'aichat.error': 'Failed to get AI response. Please try again.',
    'aichat.uploading': 'Uploading image and recognizing text…',
    'aichat.ocr_result': 'OCR result:',
    'aichat.translated': 'Translated:',
    'aichat.ocr_error': 'Failed to recognize or translate the image.',
  },
  fr: {
    'hero.title': 'Your Magical Travel Companion',
    'hero.subtitle': 'AI-powered travel planning with seamless connectivity worldwide',
    'hero.cta': 'Start Planning',
    'features.ai': 'AI Planning',
    'features.esim': 'Global eSIM',
    'features.realtime': 'Real-time Updates',
    'nav.home': 'Home',
    'nav.plan': 'Plan Trip',
    'nav.dashboard': 'Dashboard',
    'planning.destination': 'Where would you like to go?',
    'planning.dates': 'When are you traveling?',
    'planning.budget': 'What\'s your budget?',
    'planning.style': 'Travel Style',
    'planning.companions': 'Who\'s joining you?',
    // PaymentScreen (enコピー)
    'paymentscreen.title': 'Payment',
    'paymentscreen.no_plan': 'No plan selected.',
    'paymentscreen.agree': 'I agree to the Terms of Service',
    'paymentscreen.pay': 'Pay with Stripe',
    'paymentscreen.note': 'You will be redirected to Stripe for secure payment.',
    'paymentscreen.secure': 'Your payment is protected by Stripe.',
    // QRCodeScreen (enコピー)
    'qrscreen.title': 'eSIM Activation',
    'qrscreen.no_plan': 'No plan selected.',
    'qrscreen.desc': 'Scan the QR code below to activate your eSIM.',
    'qrscreen.loading': 'Issuing your eSIM... Please wait.',
    'qrscreen.copy': 'Copy QR URL',
    'qrscreen.download': 'Download QR',
    'qrscreen.note': 'If you have trouble, contact support.',
    'qrscreen.copied': 'Copied!',
    'qrscreen.step1': 'Open your device settings and select "Add Mobile Plan".',
    'qrscreen.step2': 'Scan the QR code above with your device.',
    'qrscreen.step3': 'Follow the on-screen instructions to complete activation.',
    'qrscreen.goto_dashboard': 'Go to Dashboard',
    // Dashboard (enコピー)
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading your plans...',
    'dashboard.no_plans': 'No travel plans found.',
    'dashboard.active': 'Active',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.completed': 'Completed',
    'dashboard.details': 'Details',
    'dashboard.show_qr': 'Show eSIM QR',
    'dashboard.esim_active': 'eSIM Active',
    'dashboard.esim_expired': 'eSIM Expired',
    'dashboard.esim_pending': 'eSIM Pending',
    // Review (enコピー)
    'review.title': 'User Reviews',
    'review.your_rating': 'Your Rating',
    'review.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.latest': 'Latest Reviews',
    'review.loading': 'Loading reviews...',
    'review.no_reviews': 'No reviews yet.',
    // FAQ (enコピー)
    'faq.title': 'Frequently Asked Questions',
    'faq.search': 'Search FAQ...',
    'faq.all': 'All',
    'faq.loading': 'Loading FAQs...',
    'faq.no_results': 'No FAQs found.',
    // AdminDashboard (enコピー)
    'admin.title': 'Admin Dashboard',
    'admin.tab_users': 'Users',
    'admin.tab_plans': 'Plans',
    'admin.tab_faqs': 'FAQs',
    'admin.tab_reviews': 'Reviews',
    'admin.users': 'User Management',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.plans': 'Plan Management',
    'admin.price': 'Price',
    'admin.faqs': 'FAQ Management',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.category': 'Category',
    'admin.reviews': 'Review Management',
    'admin.user': 'User',
    'admin.comment': 'Comment',
    'admin.rating': 'Rating',
    'admin.date': 'Date',
    'admin.kpi_mau': 'Monthly Active Users',
    'admin.kpi_new_users': 'New Users',
    'admin.kpi_sales': 'Sales',
    'admin.kpi_esim': 'eSIM Issued',
    'admin.kpi_sales_trend': 'Sales Trend (¥)',
    'admin.kpi_esim_trend': 'eSIM Issued Trend',
    // AIChat (enコピー)
    'aichat.placeholder': 'Ask about your trip, edit your plan, or get local support…',
    'aichat.thinking': 'AI is thinking…',
    'aichat.default_reply': 'Thank you for your question. Here is a detailed answer.',
    'aichat.error': 'Failed to get AI response. Please try again.',
    'aichat.uploading': 'Uploading image and recognizing text…',
    'aichat.ocr_result': 'OCR result:',
    'aichat.translated': 'Translated:',
    'aichat.ocr_error': 'Failed to recognize or translate the image.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};