import React, { useState, createContext, useContext, useEffect } from 'react'

// Available languages
const languages = {
  en: {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    font: 'Poppins',
    pageTitle: 'Trippin - AI Travel Planner for Japan',
    translations: {
      // 既存の翻訳に加えて新しい翻訳を追加
      welcome: 'Welcome to Trippin',
      selectLanguage: 'Choose your language to continue',
      selectEsimPlan: 'Choose your Japan eSIM plan',
      selectedPlan: 'Selected Plan',
      payment: 'Payment',
      scanQR: 'Scan QR Code to activate your eSIM',
      complete: 'Thank you for your purchase!',
      continue: 'Continue',
      back: 'Back',
      cancel: 'Cancel',
      confirm: 'Confirm',
      home: 'Home',
      days: 'Days',
      gb: 'GB',
      price: 'Price',
      duration: 'Duration',
      data: 'Data',
      pay: 'Pay',
      processing: 'Processing...',
      
      // 旅行プランナー用翻訳
      aiTravelPlanner: 'AI Travel Planner',
      planYourPerfectTrip: 'Plan your perfect Japan trip',
      greeting: 'Hello! I\'m Trippin\'s AI Travel Planner 🦊 Let\'s create your perfect Japan trip together!',
      startPlanning: 'Start Planning My Trip',
      learnMore: 'Learn More About Trippin',
      askDestination: 'First, where in Japan would you like to visit? Let me suggest some popular destinations!',
      askDates: 'Great choice! When are you planning to travel?',
      askBudget: 'What\'s your budget range? (per person)',
      askTravelStyle: 'What\'s your preferred travel style?',
      askInterests: 'What are you most interested in? (select multiple)',
      askAccommodation: 'What type of accommodation do you prefer?',
      askTransportation: 'How would you like to get around?',
      generatingPlans: 'Excellent! I\'m creating 3 special travel plans based on your preferences...',
      plansReady: 'Your perfect travel plans are ready! 🎉 I\'ve prepared 3 options for you. Which one catches your eye?',
      planDetails: 'Plan Details',
      selectPlan: 'Select This Plan',
      bookEsim: 'Book Complete Package',
      totalCost: 'Total Cost',
      perPerson: '(per person)',
      day: 'Day',
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
      breakfast: 'Breakfast',
      lunch: 'Lunch',
      dinner: 'Dinner',
      accommodation: 'Accommodation',
      transportation: 'Transportation',
      activities: 'Activities',
      food: 'Food',
      esim: 'eSIM',
      budget: 'Budget',
      itinerary: 'Itinerary',
      highlights: 'Highlights',
      aiInsights: 'AI Insights',
      
      // 予約フロー用翻訳
      existingBookingsTitle: 'Existing Bookings Check',
      existingBookingsDesc: 'Do you already have flight and hotel bookings for your Japan trip?',
      flightBooking: 'Flight Booking',
      flightBookingQuestion: 'Do you already have your flight to Japan booked?',
      hotelBooking: 'Hotel Booking',
      hotelBookingQuestion: 'Do you already have your accommodation in Japan booked?',
      yes: 'Yes, already booked',
      no: 'No, need to book',
      selectDataPlan: 'Select Your Data Plan',
      dataPlanDescription: 'Choose how much data you\'ll need for your Japan trip. 1GB plan is included free!',
      dataPlan1GB: 'Basic Plan',
      dataPlan1GBDesc: 'Perfect for light usage - maps, messaging, and essential apps',
      dataPlan3GB: 'Standard Plan',
      dataPlan3GBDesc: 'Great for social media, photos, and moderate streaming',
      dataPlan5GB: 'Premium Plan',
      dataPlan5GBDesc: 'Ideal for heavy usage, video calls, and content creation',
      dataPlan10GB: 'Ultimate Plan',
      dataPlan10GBDesc: 'Unlimited usage for power users and content creators',
      free: 'FREE',
      recommended: 'Recommended',
      continueWithPlan: 'Continue with',
      travelerInformation: 'Traveler Information',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email Address',
      phone: 'Phone Number',
      dateOfBirth: 'Date of Birth',
      completeBooking: 'Complete Booking',
      bookingConfirmed: 'Booking Confirmed!',
      bookingSummary: 'Booking Summary',
      travelPlan: 'Travel Plan',
      dataPlan: 'Data Plan',
      confirmationNumbers: 'Confirmation Numbers',
      returnToHome: 'Return to Home',
      
      // 既存の翻訳
      acceptTermsMessage: 'Please accept the terms and conditions to proceed with payment.',
      paymentMethods: 'Payment Methods',
      creditCard: 'Credit Card',
      creditCardDesc: 'Visa, Mastercard, AMEX',
      applePay: 'Apple Pay',
      applePayDesc: 'Fast & secure',
      qrPayment: 'QR Payment',
      qrPaymentDesc: 'WeChat Pay, Alipay',
      mobilePayment: 'Mobile Payment',
      mobilePaymentDesc: 'PayPay, LINE Pay',
      cashPayment: 'Cash Payment',
      cashPaymentDesc: 'Pay at convenience store',
      viewTerms: 'View Terms & Conditions',
      termsTitle: 'Terms & Conditions',
      agreeTerms: 'I agree to the Terms & Conditions',
      scanInstructions: 'Scan this QR code with your phone to activate your eSIM',
      downloadComplete: 'Download Complete',
      restart: 'New Purchase',
      planBasic: 'Japan Basic',
      planStandard: 'Japan Standard',
      planPremium: 'Japan Premium',
      planTest: 'Test Plan',
      planTestDesc: 'Perfect for testing!',
      planTestButton: 'Try Free',
      planBasicDesc: 'Essential connectivity',
      planStandardDesc: 'Popular choice',
      planPremiumDesc: 'Maximum coverage',
      featureHighSpeed: 'High-speed Data',
      featureJapanCoverage: 'Japan Coverage',
      featureEasyActivation: 'Easy Setup',
      featureHotspot: 'Mobile Hotspot',
      featurePrioritySupport: 'Priority Support',
      securePayments: 'Secure Payment',
      instantActivation: 'Instant Activation',
      globalCoverage: 'Global Coverage',
      daysUnit: 'Days',
      gbUnit: 'GB',
      purchase: 'Purchase',
      loginRequired: 'Login Required',
      loginRequiredMessage: 'Please log in to access the purchase page',
      getQrCode: 'Get the QR Code',
      currency: 'Currency',
      changeCurrency: 'Change Currency',
      plan: 'Plan',
      orderId: 'Order ID',
      orderDetails: 'Order Details',
      freePlan: 'Free Test Plan',
      noCharge: 'No charge',
      confirmationSent: '✅ Confirmation email sent! Check your inbox for the QR code and activation instructions.',
      printQrCode: 'Print QR Code',
      downloadQR: 'Download QR',
      esimCompatibleDevices: 'eSIM Compatible Devices',
      
      // Footer translations
      makeYourTripPerfect: 'Make Your Trip Perfect',
      beyondEsim: 'Beyond eSIM - we help you discover, save, and enjoy Japan',
      findStorage: 'Find Luggage Storage',
      bookTravel: 'Book Travel & Hotels',
      
      // その他の既存翻訳...
      japanEsimForTravelers: 'Japan eSIM for travelers',
      devices: 'Devices',
      account: 'Account',
      authenticating: 'Authenticating...',
      
      auth: {
        login: 'Log In',
        register: 'Sign Up',
        createAccount: 'Create Account',
        emailLogin: 'Email Login',
        smsLogin: 'SMS Login',
        email: 'Email',
        phone: 'Phone Number',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        forgotPassword: 'Forgot Password?',
        resetPassword: 'Reset Password',
        verificationCode: 'Verification Code',
        sendCode: 'Send Code',
        resendCode: 'Resend Code',
        verify: 'Verify',
        verifyAccount: 'Verify Your Account',
        checkEmail: 'Please check your email for the verification link',
        enterSMSCode: 'Enter the verification code sent to your phone',
        alreadyHaveAccount: 'Already have an account? Log in',
        needAccount: 'Need an account? Sign up',
        orContinueWith: 'Or continue with',
        continueWithGoogle: 'Continue with Google',
        continueWithApple: 'Continue with Apple',
        continueWithFacebook: 'Continue with Facebook',
        continueWithLine: 'Continue with LINE',
        continueWithWechat: 'Continue with WeChat',
        continueWithTwitter: 'Continue with Twitter',
        accountSettings: 'Account Settings',
        purchaseHistory: 'Purchase History',
        logout: 'Log Out',
        profile: 'Profile',
        myQrCodes: 'My QR Codes',
        verificationRequired: 'Verification Required',
        invalidEmail: 'Invalid email address',
        invalidPhone: 'Invalid phone number',
        invalidPassword: 'Password must be at least 8 characters',
        passwordMismatch: 'Passwords do not match',
        invalidCode: 'Invalid verification code',
        codeSent: 'Verification code sent',
        emailSent: 'Verification email sent',
        accountCreated: 'Account created successfully',
        loginSuccessful: 'Login successful',
        verificationSuccess: 'Verification successful',
        authRequired: 'Authentication Required',
        pleaseLoginOrRegister: 'Please log in or sign up to continue',
        continueToPayment: 'Continue to payment',
        socialLogin: 'Social Login',
      },
    },
  },
  ja: {
    code: 'ja',
    name: '日本語',
    flag: '🇯🇵',
    font: 'Noto Sans JP',
    pageTitle: 'Trippin - AI旅行プランナー',
    translations: {
      welcome: 'Trippinへようこそ',
      selectLanguage: '言語を選択して続行してください',
      selectEsimPlan: '日本eSIMプランを選択',
      selectedPlan: '選択されたプラン',
      payment: 'お支払い',
      scanQR: 'QRコードをスキャンしてeSIMを有効化',
      complete: 'ご購入ありがとうございます！',
      continue: '続ける',
      back: '戻る',
      cancel: 'キャンセル',
      confirm: '確認',
      home: 'ホーム',
      days: '日間',
      gb: 'GB',
      price: '価格',
      duration: '期間',
      data: 'データ量',
      pay: '支払う',
      processing: '処理中...',
      
      // 旅行プランナー用翻訳
      aiTravelPlanner: 'AI旅行プランナー',
      planYourPerfectTrip: '完璧な日本旅行を計画しましょう',
      greeting: 'こんにちは！私はTrippinのAI旅行プランナーです🦊 あなたの完璧な日本旅行を一緒に計画しましょう！',
      startPlanning: '旅行プランを作成する',
      learnMore: 'Trippinについて詳しく',
      askDestination: 'まず、日本のどちらに行きたいですか？人気の目的地をいくつか提案しますね！',
      askDates: '素晴らしい選択ですね！いつ頃の旅行を予定していますか？',
      askBudget: '予算はどのくらいを考えていますか？（1人あたり）',
      askTravelStyle: 'どのような旅行スタイルがお好みですか？',
      askInterests: '特に興味のあることを教えてください（複数選択可）',
      askAccommodation: '宿泊施設のご希望はありますか？',
      askTransportation: '移動手段のご希望はありますか？',
      generatingPlans: '素晴らしい！あなたの好みに基づいて、3つの特別な旅行プランを作成しています...',
      plansReady: '完璧な旅行プランが完成しました！🎉 3つのプランをご用意しました。どれがお気に入りですか？',
      planDetails: 'プランの詳細',
      selectPlan: 'このプランを選択',
      bookEsim: '完全パッケージを予約',
      totalCost: '総費用',
      perPerson: '（1人あたり）',
      day: '日目',
      morning: '午前',
      afternoon: '午後',
      evening: '夜',
      breakfast: '朝食',
      lunch: '昼食',
      dinner: '夕食',
      accommodation: '宿泊',
      transportation: '交通',
      activities: 'アクティビティ',
      food: '食事',
      esim: 'eSIM',
      budget: '予算',
      itinerary: '旅程',
      highlights: 'ハイライト',
      aiInsights: 'AIからのアドバイス',
      
      // 予約フロー用翻訳
      existingBookingsTitle: '既存予約の確認',
      existingBookingsDesc: '日本旅行の航空券とホテルの予約はお済みですか？',
      flightBooking: '航空券予約',
      flightBookingQuestion: '日本への航空券はすでに予約済みですか？',
      hotelBooking: 'ホテル予約',
      hotelBookingQuestion: '日本での宿泊施設はすでに予約済みですか？',
      yes: 'はい、予約済み',
      no: 'いいえ、予約が必要',
      selectDataPlan: 'データプランを選択',
      dataPlanDescription: '日本旅行で必要なデータ量を選択してください。1GBプランは無料で含まれています！',
      dataPlan1GB: 'ベーシックプラン',
      dataPlan1GBDesc: '軽い使用に最適 - 地図、メッセージ、必須アプリ',
      dataPlan3GB: 'スタンダードプラン',
      dataPlan3GBDesc: 'SNS、写真、適度なストリーミングに最適',
      dataPlan5GB: 'プレミアムプラン',
      dataPlan5GBDesc: 'ヘビーユーザー、ビデオ通話、コンテンツ作成に最適',
      dataPlan10GB: 'アルティメットプラン',
      dataPlan10GBDesc: 'パワーユーザーとコンテンツクリエイター向け無制限使用',
      free: '無料',
      recommended: 'おすすめ',
      continueWithPlan: 'このプランで続行',
      travelerInformation: '旅行者情報',
      firstName: '名',
      lastName: '姓',
      email: 'メールアドレス',
      phone: '電話番号',
      dateOfBirth: '生年月日',
      completeBooking: '予約を完了',
      bookingConfirmed: '予約が確定しました！',
      bookingSummary: '予約概要',
      travelPlan: '旅行プラン',
      dataPlan: 'データプラン',
      confirmationNumbers: '確認番号',
      returnToHome: 'ホームに戻る',
      
      // 既存の翻訳
      acceptTermsMessage: '支払いを続行するには利用規約に同意してください。',
      paymentMethods: 'お支払い方法',
      creditCard: 'クレジットカード',
      creditCardDesc: 'Visa、Mastercard、AMEX',
      applePay: 'Apple Pay',
      applePayDesc: '簡単・安全',
      qrPayment: 'QR決済',
      qrPaymentDesc: 'WeChat Pay、Alipay',
      mobilePayment: 'モバイル決済',
      mobilePaymentDesc: 'PayPay、LINE Pay',
      cashPayment: '現金決済',
      cashPaymentDesc: 'コンビニでお支払い',
      viewTerms: '利用規約を表示',
      termsTitle: '利用規約',
      agreeTerms: '利用規約に同意します',
      scanInstructions: 'このQRコードをスキャンしてeSIMを有効化してください',
      downloadComplete: 'ダウンロード完了',
      restart: '新規購入を開始',
      planBasic: 'Japan Basic',
      planStandard: 'Japan Standard',
      planPremium: 'Japan Premium',
      planTest: 'テストプラン',
      planTestDesc: 'テストに最適！',
      planTestButton: '無料で試す',
      planBasicDesc: '基本的な接続',
      planStandardDesc: '人気の選択',
      planPremiumDesc: '最大カバレッジ',
      featureHighSpeed: '高速データ通信',
      featureJapanCoverage: '日本全国対応',
      featureEasyActivation: '簡単設定',
      featureHotspot: 'テザリング対応',
      featurePrioritySupport: '優先サポート',
      securePayments: '安全な決済',
      instantActivation: '即時利用可能',
      globalCoverage: '世界対応',
      daysUnit: '日間',
      gbUnit: 'GB',
      purchase: '購入',
      loginRequired: 'ログインが必要です',
      loginRequiredMessage: '購入ページにアクセスするにはログインしてください',
      getQrCode: 'QRコードを取得',
      currency: '通貨',
      changeCurrency: '通貨を変更',
      plan: 'プラン',
      orderId: '注文ID',
      orderDetails: '注文詳細',
      freePlan: '無料テストプラン',
      noCharge: '料金なし',
      confirmationSent: '✅ 確認メールを送信しました！QRコードと有効化手順についてメールボックスをご確認ください。',
      printQrCode: 'QRコードを印刷',
      downloadQR: 'QRダウンロード',
      esimCompatibleDevices: 'eSIM対応デバイス',
      
      // Footer translations
      makeYourTripPerfect: '完璧な旅行にしましょう',
      beyondEsim: 'eSIMを超えて - 日本の発見、節約、楽しみをお手伝い',
      findStorage: '荷物預かり所を探す',
      bookTravel: '旅行・ホテルを予約',
      
      japanEsimForTravelers: '旅行者向け日本eSIM',
      devices: 'デバイス',
      account: 'アカウント',
      authenticating: '認証中...',
      
      auth: {
        login: 'ログイン',
        register: '会員登録',
        createAccount: 'アカウント作成',
        emailLogin: 'メールアドレスでログイン',
        smsLogin: 'SMSでログイン',
        socialLogin: 'ソーシャルログイン',
        email: 'メールアドレス',
        phone: '電話番号',
        password: 'パスワード',
        confirmPassword: 'パスワード確認',
        forgotPassword: 'パスワードをお忘れの方',
        resetPassword: 'パスワードをリセット',
        verificationCode: '認証コード',
        sendCode: 'コードを送信',
        resendCode: 'コードを再送信',
        verify: '確認',
        verifyAccount: 'アカウントを確認',
        checkEmail: '確認用メールをご確認ください',
        enterSMSCode: '携帯電話に送信された認証コードを入力してください',
        alreadyHaveAccount: 'すでにアカウントをお持ちですか？ログイン',
        needAccount: 'アカウントが必要ですか？登録',
        orContinueWith: 'または以下で続ける',
        continueWithGoogle: 'Googleで続行',
        continueWithApple: 'Appleで続行',
        continueWithFacebook: 'Facebookで続行',
        continueWithLine: 'LINEで続行',
        continueWithWechat: 'WeChatで続行',
        continueWithTwitter: 'Twitterで続行',
        accountSettings: 'アカウント設定',
        purchaseHistory: '購入履歴',
        logout: 'ログアウト',
        profile: 'プロフィール',
        myQrCodes: 'マイQRコード',
        verificationRequired: '認証が必要です',
        invalidEmail: '無効なメールアドレスです',
        invalidPhone: '無効な電話番号です',
        invalidPassword: 'パスワードは8文字以上である必要があります',
        passwordMismatch: 'パスワードが一致しません',
        invalidCode: '無効な認証コードです',
        codeSent: '認証コードが送信されました',
        emailSent: '確認メールが送信されました',
        accountCreated: 'アカウントが正常に作成されました',
        loginSuccessful: 'ログイン成功',
        verificationSuccess: '認証成功',
        authRequired: '認証が必要です',
        pleaseLoginOrRegister: '続行するにはログインまたは登録してください',
        continueToPayment: '支払いに進む',
      },
    },
  },
  zh: {
    code: 'zh',
    name: '中文',
    flag: '🇨🇳',
    font: 'Noto Sans SC',
    pageTitle: 'Trippin - AI旅行规划师',
    translations: {
      welcome: '欢迎使用Trippin',
      selectLanguage: '选择您的语言以继续',
      selectEsimPlan: '选择您的日本eSIM套餐',
      selectedPlan: '已选择的套餐',
      payment: '支付',
      scanQR: '扫描二维码激活eSIM',
      complete: '感谢您的购买！',
      continue: '继续',
      back: '返回',
      cancel: '取消',
      confirm: '确认',
      home: '首页',
      days: '天',
      gb: 'GB',
      price: '价格',
      duration: '有效期',
      data: '数据量',
      pay: '支付',
      processing: '处理中...',
      
      // 旅行プランナー用翻訳
      aiTravelPlanner: 'AI旅行规划师',
      planYourPerfectTrip: '规划您完美的日本之旅',
      greeting: '您好！我是Trippin的AI旅行规划师🦊 让我们一起规划您完美的日本之旅！',
      startPlanning: '开始规划我的旅行',
      learnMore: '了解更多关于Trippin',
      askDestination: '首先，您想去日本的哪里？让我为您推荐一些热门目的地！',
      askDates: '很好的选择！您计划什么时候旅行？',
      askBudget: '您的预算范围是多少？（每人）',
      askTravelStyle: '您喜欢什么样的旅行风格？',
      askInterests: '您最感兴趣的是什么？（可多选）',
      askAccommodation: '您喜欢什么类型的住宿？',
      askTransportation: '您希望如何出行？',
      generatingPlans: '太好了！我正在根据您的喜好制定3个特别的旅行计划...',
      plansReady: '您的完美旅行计划已准备就绪！🎉 我为您准备了3个选择。哪一个吸引您？',
      planDetails: '计划详情',
      selectPlan: '选择此计划',
      bookEsim: '预订完整套餐',
      totalCost: '总费用',
      perPerson: '（每人）',
      day: '第',
      morning: '上午',
      afternoon: '下午',
      evening: '晚上',
      breakfast: '早餐',
      lunch: '午餐',
      dinner: '晚餐',
      accommodation: '住宿',
      transportation: '交通',
      activities: '活动',
      food: '餐饮',
      esim: 'eSIM',
      budget: '预算',
      itinerary: '行程',
      highlights: '亮点',
      aiInsights: 'AI建议',
      
      // 预订流程翻译
      existingBookingsTitle: '现有预订检查',
      existingBookingsDesc: '您是否已经预订了日本之旅的机票和酒店？',
      flightBooking: '机票预订',
      flightBookingQuestion: '您是否已经预订了前往日本的机票？',
      hotelBooking: '酒店预订',
      hotelBookingQuestion: '您是否已经预订了在日本的住宿？',
      yes: '是的，已预订',
      no: '否，需要预订',
      selectDataPlan: '选择您的数据套餐',
      dataPlanDescription: '选择您在日本旅行期间需要的数据量。1GB套餐免费包含！',
      dataPlan1GB: '基础套餐',
      dataPlan1GBDesc: '适合轻度使用 - 地图、消息和必需应用',
      dataPlan3GB: '标准套餐',
      dataPlan3GBDesc: '适合社交媒体、照片和适度流媒体',
      dataPlan5GB: '高级套餐',
      dataPlan5GBDesc: '适合重度使用、视频通话和内容创作',
      dataPlan10GB: '终极套餐',
      dataPlan10GBDesc: '为重度用户和内容创作者提供无限使用',
      free: '免费',
      recommended: '推荐',
      continueWithPlan: '继续使用',
      travelerInformation: '旅行者信息',
      firstName: '名',
      lastName: '姓',
      email: '电子邮箱',
      phone: '电话号码',
      dateOfBirth: '出生日期',
      completeBooking: '完成预订',
      bookingConfirmed: '预订已确认！',
      bookingSummary: '预订摘要',
      travelPlan: '旅行计划',
      dataPlan: '数据套餐',
      confirmationNumbers: '确认号码',
      returnToHome: '返回首页',
      
      // 既存の翻訳
      acceptTermsMessage: '请接受条款和条件以继续支付。',
      paymentMethods: '支付方式',
      creditCard: '信用卡',
      creditCardDesc: 'Visa、Mastercard、AMEX',
      applePay: 'Apple Pay',
      applePayDesc: '快速安全',
      qrPayment: '扫码支付',
      qrPaymentDesc: '微信支付、支付宝',
      mobilePayment: '移动支付',
      mobilePaymentDesc: 'PayPay、LINE Pay',
      cashPayment: '现金支付',
      cashPaymentDesc: '便利店支付',
      viewTerms: '查看条款和条件',
      termsTitle: '条款和条件',
      agreeTerms: '我同意条款和条件',
      scanInstructions: '扫描此二维码激活您的eSIM',
      downloadComplete: '下载完成',
      restart: '开始新购买',
      planBasic: 'Japan Basic',
      planStandard: 'Japan Standard',
      planPremium: 'Japan Premium',
      planTest: '测试套餐',
      planTestDesc: '测试的完美选择！',
      planTestButton: '免费试用',
      planBasicDesc: '基本连接',
      planStandardDesc: '热门选择',
      planPremiumDesc: '最大覆盖',
      featureHighSpeed: '高速数据',
      featureJapanCoverage: '日本覆盖',
      featureEasyActivation: '简单激活',
      featureHotspot: '热点共享',
      featurePrioritySupport: '优先支持',
      securePayments: '安全支付',
      instantActivation: '即时激活',
      globalCoverage: '全球覆盖',
      daysUnit: '天',
      gbUnit: 'GB',
      purchase: '购买',
      loginRequired: '需要登录',
      loginRequiredMessage: '请登录以访问购买页面',
      getQrCode: '获取二维码',
      currency: '货币',
      changeCurrency: '更改货币',
      plan: '套餐',
      orderId: '订单号',
      orderDetails: '订单详情',
      freePlan: '免费测试套餐',
      noCharge: '免费',
      confirmationSent: '✅ 确认邮件已发送！请查看您的邮箱获取二维码和激活说明。',
      printQrCode: '打印二维码',
      downloadQR: '下载二维码',
      esimCompatibleDevices: 'eSIM兼容设备',
      
      // Footer translations
      makeYourTripPerfect: '让您的旅行更完美',
      beyondEsim: '不仅仅是eSIM - 我们帮助您发现、节省和享受日本',
      findStorage: '查找行李寄存',
      bookTravel: '预订旅行和酒店',
      
      japanEsimForTravelers: '为旅行者提供的日本eSIM',
      devices: '设备',
      account: '账户',
      authenticating: '认证中...',
      
      auth: {
        login: '登录',
        register: '注册账号',
        createAccount: '创建账户',
        emailLogin: '邮箱登录',
        smsLogin: '短信验证',
        socialLogin: '社交登录',
        email: '电子邮箱',
        phone: '手机号码',
        password: '密码',
        confirmPassword: '确认密码',
        forgotPassword: '忘记密码？',
        resetPassword: '重置密码',
        verificationCode: '验证码',
        sendCode: '发送验证码',
        resendCode: '重新发送',
        verify: '验证',
        verifyAccount: '验证您的账户',
        checkEmail: '请检查您的邮箱以获取验证链接',
        enterSMSCode: '请输入发送到您手机的验证码',
        alreadyHaveAccount: '已有账户？登录',
        needAccount: '还没有账号？立即注册',
        orContinueWith: '或继续使用',
        continueWithGoogle: '使用Google继续',
        continueWithApple: '使用Apple继续',
        continueWithFacebook: '使用Facebook继续',
        continueWithLine: '使用LINE继续',
        continueWithWechat: '使用微信继续',
        continueWithTwitter: '使用Twitter继续',
        accountSettings: '账户设置',
        purchaseHistory: '购买历史',
        logout: '退出登录',
        profile: '个人资料',
        myQrCodes: '我的二维码',
        verificationRequired: '需要验证',
        invalidEmail: '无效的邮箱地址',
        invalidPhone: '无效的手机号码',
        invalidPassword: '密码必须至少8个字符',
        passwordMismatch: '密码不匹配',
        invalidCode: '无效的验证码',
        codeSent: '验证码已发送',
        emailSent: '验证邮件已发送',
        accountCreated: '账户创建成功',
        loginSuccessful: '登录成功',
        verificationSuccess: '验证成功',
        authRequired: '需要认证',
        pleaseLoginOrRegister: '请登录或注册以继续',
        continueToPayment: '继续支付',
      },
    },
  },
  ko: {
    code: 'ko',
    name: '한국어',
    flag: '🇰🇷',
    font: 'Noto Sans KR',
    pageTitle: 'Trippin - AI 여행 플래너',
    translations: {
      welcome: 'Trippin에 오신 것을 환영합니다',
      selectLanguage: '언어를 선택하여 계속하세요',
      selectEsimPlan: '일본 eSIM 플랜 선택',
      selectedPlan: '선택된 플랜',
      payment: '결제',
      scanQR: 'QR 코드를 스캔하여 eSIM 활성화',
      complete: '구매해 주셔서 감사합니다!',
      continue: '계속',
      back: '뒤로',
      cancel: '취소',
      confirm: '확인',
      home: '홈',
      days: '일',
      gb: 'GB',
      price: '가격',
      duration: '기간',
      data: '데이터',
      pay: '결제',
      processing: '처리 중...',
      
      // 旅行プランナー用翻訳
      aiTravelPlanner: 'AI 여행 플래너',
      planYourPerfectTrip: '완벽한 일본 여행을 계획하세요',
      greeting: '안녕하세요! 저는 Trippin의 AI 여행 플래너입니다🦊 완벽한 일본 여행을 함께 계획해봐요!',
      startPlanning: '여행 계획 시작하기',
      learnMore: 'Trippin에 대해 더 알아보기',
      askDestination: '먼저 일본의 어디를 방문하고 싶으신가요? 인기 있는 목적지를 추천해드릴게요!',
      askDates: '좋은 선택이네요! 언제 여행을 계획하고 계신가요?',
      askBudget: '예산은 어느 정도로 생각하고 계신가요? (1인당)',
      askTravelStyle: '어떤 여행 스타일을 선호하시나요?',
      askInterests: '특히 관심 있는 것은 무엇인가요? (복수 선택 가능)',
      askAccommodation: '어떤 숙박시설을 선호하시나요?',
      askTransportation: '어떻게 이동하고 싶으신가요?',
      generatingPlans: '훌륭해요! 당신의 취향에 맞는 3가지 특별한 여행 계획을 만들고 있어요...',
      plansReady: '완벽한 여행 계획이 준비되었습니다! 🎉 3가지 옵션을 준비했어요. 어떤 것이 마음에 드시나요?',
      planDetails: '계획 상세',
      selectPlan: '이 계획 선택',
      bookEsim: '완전 패키지 예약',
      totalCost: '총 비용',
      perPerson: '(1인당)',
      day: '일차',
      morning: '오전',
      afternoon: '오후',
      evening: '저녁',
      breakfast: '아침식사',
      lunch: '점심식사',
      dinner: '저녁식사',
      accommodation: '숙박',
      transportation: '교통',
      activities: '액티비티',
      food: '음식',
      esim: 'eSIM',
      budget: '예산',
      itinerary: '일정',
      highlights: '하이라이트',
      aiInsights: 'AI 조언',
      
      // 예약 플로우 번역
      existingBookingsTitle: '기존 예약 확인',
      existingBookingsDesc: '일본 여행의 항공편과 호텔을 이미 예약하셨나요?',
      flightBooking: '항공편 예약',
      flightBookingQuestion: '일본행 항공편을 이미 예약하셨나요?',
      hotelBooking: '호텔 예약',
      hotelBookingQuestion: '일본에서의 숙박을 이미 예약하셨나요?',
      yes: '네, 이미 예약했습니다',
      no: '아니요, 예약이 필요합니다',
      selectDataPlan: '데이터 플랜 선택',
      dataPlanDescription: '일본 여행 중 필요한 데이터 양을 선택하세요. 1GB 플랜은 무료로 포함됩니다!',
      dataPlan1GB: '기본 플랜',
      dataPlan1GBDesc: '가벼운 사용에 적합 - 지도, 메시지, 필수 앱',
      dataPlan3GB: '표준 플랜',
      dataPlan3GBDesc: 'SNS, 사진, 적당한 스트리밍에 적합',
      dataPlan5GB: '프리미엄 플랜',
      dataPlan5GBDesc: '무거운 사용, 영상 통화, 콘텐츠 제작에 적합',
      dataPlan10GB: '얼티밋 플랜',
      dataPlan10GBDesc: '파워 유저와 콘텐츠 크리에이터를 위한 무제한 사용',
      free: '무료',
      recommended: '추천',
      continueWithPlan: '이 플랜으로 계속',
      travelerInformation: '여행자 정보',
      firstName: '이름',
      lastName: '성',
      email: '이메일 주소',
      phone: '전화번호',
      dateOfBirth: '생년월일',
      completeBooking: '예약 완료',
      bookingConfirmed: '예약이 확인되었습니다!',
      bookingSummary: '예약 요약',
      travelPlan: '여행 계획',
      dataPlan: '데이터 플랜',
      confirmationNumbers: '확인 번호',
      returnToHome: '홈으로 돌아가기',
      
      // 既存의翻訳
      acceptTermsMessage: '결제를 계속하려면 이용약관에 동의해주세요.',
      paymentMethods: '결제 방법',
      creditCard: '신용카드',
      creditCardDesc: 'Visa、Mastercard、AMEX',
      applePay: 'Apple Pay',
      applePayDesc: '빠르고 안전한 결제',
      qrPayment: 'QR 결제',
      qrPaymentDesc: '위챗페이, 알리페이',
      mobilePayment: '모바일 결제',
      mobilePaymentDesc: 'PayPay, LINE Pay',
      cashPayment: '현금 결제',
      cashPaymentDesc: '편의점에서 결제',
      viewTerms: '이용약관 보기',
      termsTitle: '이용약관',
      agreeTerms: '이용약관에 동의합니다',
      scanInstructions: '이 QR 코드를 스캔하여 eSIM을 활성화하세요',
      downloadComplete: '다운로드 완료',
      restart: '새 구매 시작',
      planBasic: 'Japan Basic',
      planStandard: 'Japan Standard',
      planPremium: 'Japan Premium',
      planTest: '테스트 플랜',
      planTestDesc: '테스트에 완벽!',
      planTestButton: '무료 체험',
      planBasicDesc: '기본 연결',
      planStandardDesc: '인기 선택',
      planPremiumDesc: '최대 커버리지',
      featureHighSpeed: '고속 데이터',
      featureJapanCoverage: '일본 커버리지',
      featureEasyActivation: '간편 활성화',
      featureHotspot: '핫스팟 포함',
      featurePrioritySupport: '우선 지원',
      securePayments: '안전한 결제',
      instantActivation: '즉시 활성화',
      globalCoverage: '글로벌 커버리지',
      daysUnit: '일',
      gbUnit: 'GB',
      purchase: '구매',
      loginRequired: '로그인 필요',
      loginRequiredMessage: '구매 페이지에 접근하려면 로그인하세요',
      getQrCode: 'QR 코드 받기',
      currency: '통화',
      changeCurrency: '통화 변경',
      plan: '플랜',
      orderId: '주문 번호',
      orderDetails: '주문 상세',
      freePlan: '무료 테스트 플랜',
      noCharge: '무료',
      confirmationSent: '✅ 확인 이메일이 발송되었습니다! QR 코드와 활성화 지침을 위해 메일함을 확인해주세요.',
      printQrCode: 'QR 코드 인쇄',
      downloadQR: 'QR 다운로드',
      esimCompatibleDevices: 'eSIM 호환 기기',
      
      // Footer translations
      makeYourTripPerfect: '여행을 완벽하게 만드세요',
      beyondEsim: 'eSIM 그 이상 - 일본을 발견하고, 절약하고, 즐기도록 도와드립니다',
      findStorage: '수하물 보관소 찾기',
      bookTravel: '여행 및 호텔 예약',
      
      japanEsimForTravelers: '여행자를 위한 일본 eSIM',
      devices: '기기',
      account: '계정',
      authenticating: '인증 중...',
      
      auth: {
        login: '로그인',
        register: '회원가입',
        createAccount: '계정 만들기',
        emailLogin: '이메일로 로그인',
        smsLogin: 'SMS로 로그인',
        socialLogin: '소셜 로그인',
        email: '이메일 주소',
        phone: '전화번호',
        password: '비밀번호',
        confirmPassword: '비밀번호 확인',
        forgotPassword: '비밀번호를 잊으셨나요?',
        resetPassword: '비밀번호 재설정',
        verificationCode: '인증 코드',
        sendCode: '코드 보내기',
        resendCode: '코드 재전송',
        verify: '인증',
        verifyAccount: '계정 인증',
        checkEmail: '이메일로 전송된 인증 링크를 확인해주세요',
        enterSMSCode: '휴대폰으로 전송된 인증 코드를 입력해주세요',
        alreadyHaveAccount: '이미 계정이 있으신가요? 로그인',
        needAccount: '계정이 없으신가요? 회원가입',
        orContinueWith: '또는 다음으로 계속',
        continueWithGoogle: 'Google로 계속하기',
        continueWithApple: 'Apple로 계속하기',
        continueWithFacebook: 'Facebook으로 계속하기',
        continueWithLine: 'LINE으로 계속하기',
        continueWithWechat: 'WeChat으로 계속하기',
        continueWithTwitter: 'Twitter로 계속하기',
        accountSettings: '계정 설정',
        purchaseHistory: '구매 내역',
        logout: '로그아웃',
        profile: '프로필',
        myQrCodes: '내 QR 코드',
        verificationRequired: '인증 필요',
        invalidEmail: '유효하지 않은 이메일 주소',
        invalidPhone: '유효하지 않은 전화번호',
        invalidPassword: '비밀번호는 최소 8자 이상이어야 합니다',
        passwordMismatch: '비밀번호가 일치하지 않습니다',
        invalidCode: '유효하지 않은 인증 코드',
        codeSent: '인증 코드가 전송되었습니다',
        emailSent: '인증 이메일이 전송되었습니다',
        accountCreated: '계정이 성공적으로 생성되었습니다',
        loginSuccessful: '로그인 성공',
        verificationSuccess: '인증 성공',
        authRequired: '인증 필요',
        pleaseLoginOrRegister: '계속하려면 로그인 또는 회원가입해주세요',
        continueToPayment: '결제로 계속하기',
      },
    },
  },
}

// Create context
const LanguageContext = createContext(null)

// Provider component
export const LanguageProvider = ({ children }) => {
  // Load saved language from localStorage or detect browser language
  const getSavedLanguage = () => {
    try {
      const saved = localStorage.getItem('esim_language')
      if (saved && languages[saved]) {
        return saved
      }
    } catch (error) {
      console.log('Could not load saved language')
    }
    
    // Fallback to browser language detection
    const lang = navigator.language || navigator.languages[0]
    if (lang.startsWith('ja')) return 'ja'
    if (lang.startsWith('zh')) return 'zh'
    if (lang.startsWith('ko')) return 'ko'
    return 'en'
  }

  const [currentLanguage, setCurrentLanguage] = useState(() => {
    const langCode = getSavedLanguage()
    return languages[langCode] || languages.en
  })

  const changeLanguage = (languageCode) => {
    if (languages[languageCode]) {
      setCurrentLanguage(languages[languageCode])
      // Save to localStorage for persistence
      try {
        localStorage.setItem('esim_language', languageCode)
      } catch (error) {
        console.log('Could not save language preference')
      }
      
      // Update page title dynamically
      updatePageTitle(languages[languageCode].pageTitle)
    }
  }

  // Function to update page title
  const updatePageTitle = (title) => {
    if (typeof document !== 'undefined') {
      document.title = title
      // Also update the title element if it exists
      const titleElement = document.getElementById('page-title')
      if (titleElement) {
        titleElement.textContent = title
      }
    }
  }

  // Apply font based on language
  useEffect(() => {
    const applyFont = () => {
      const fontMap = {
        'en': '"Poppins", sans-serif',
        'ja': '"Noto Sans JP", sans-serif',
        'zh': '"Noto Sans SC", sans-serif',
        'ko': '"Noto Sans KR", sans-serif'
      }
      
      const fontFamily = fontMap[currentLanguage.code] || fontMap.en
      document.documentElement.style.setProperty('--language-font', fontFamily)
      document.body.style.fontFamily = fontFamily
    }

    applyFont()
    
    // Update page title when language changes
    updatePageTitle(currentLanguage.pageTitle)
  }, [currentLanguage])

  // Updated t() function to handle nested keys
  const t = (key) => {
    // Split the key by dots to handle nested properties
    const keys = key.split('.')
    // Start from the translations object
    let value = currentLanguage.translations

    // Traverse the nested properties
    for (const k of keys) {
      if (value && value[k] !== undefined) {
        value = value[k]
      } else {
        // If the key doesn't exist, return the key itself
        return key
      }
    }

    return value
  }

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        changeLanguage,
        t,
        languages: Object.values(languages),
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}

// Custom hook to use the language context
export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}